---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: windows
    driver:
      box: mwrock/Windows2012R2
    transport:
      name: winrm
      winrm_transport: negotiate

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[foo::default]
